package cpu6502

type Operation struct {
	Opcode      uint8
	Mnemonic    string
	Cycles      uint8
	Documented  bool
	Addressing  func(*CPU, uint16) uint16
}

// Only BRK (00) operation has no cycles here, because they're accounted for in the IRQ interrupt handler
var Opcodes [0x100] Operation = [0x100] Operation {
	{ Opcode: 0x00, Mnemonic: "BRK", Cycles: 0, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x01, Mnemonic: "ORA", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0x02, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x03, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x04, Mnemonic: "NO2", Cycles: 3, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x05, Mnemonic: "ORA", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x06, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x07, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x08, Mnemonic: "PHP", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x09, Mnemonic: "ORA", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0x0A, Mnemonic: "ASL", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x0B, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x0C, Mnemonic: "NO3", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x0D, Mnemonic: "ORA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x0E, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x0F, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x10, Mnemonic: "BPL", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x11, Mnemonic: "ORA", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0x12, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x13, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x14, Mnemonic: "NO2", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x15, Mnemonic: "ORA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x16, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x17, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x18, Mnemonic: "CLC", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x19, Mnemonic: "ORA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0x1A, Mnemonic: "NO1", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x1B, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x1C, Mnemonic: "NO3", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x1D, Mnemonic: "ORA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x1E, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x1F, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x20, Mnemonic: "JSR", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x21, Mnemonic: "AND", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0x22, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x23, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x24, Mnemonic: "BIT", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x25, Mnemonic: "AND", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x26, Mnemonic: "ROL", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x27, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x28, Mnemonic: "PLP", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x29, Mnemonic: "AND", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0x2A, Mnemonic: "ROL", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x2B, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x2C, Mnemonic: "BIT", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x2D, Mnemonic: "AND", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x2E, Mnemonic: "ROL", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x2F, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x30, Mnemonic: "BMI", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x31, Mnemonic: "AND", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0x32, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x33, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x34, Mnemonic: "NO2", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x35, Mnemonic: "AND", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x36, Mnemonic: "ROL", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x37, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x38, Mnemonic: "SEC", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x39, Mnemonic: "AND", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0x3A, Mnemonic: "NO1", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x3B, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x3C, Mnemonic: "NO3", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x3D, Mnemonic: "AND", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x3E, Mnemonic: "ROL", Cycles: 7, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x3F, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x40, Mnemonic: "RTI", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x41, Mnemonic: "EOR", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0x42, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x43, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x44, Mnemonic: "NO2", Cycles: 3, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x45, Mnemonic: "EOR", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x46, Mnemonic: "LSR", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x47, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x48, Mnemonic: "PHA", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x49, Mnemonic: "EOR", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0x4A, Mnemonic: "LSR", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x4B, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x4C, Mnemonic: "JMP", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x4D, Mnemonic: "EOR", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x4E, Mnemonic: "LSR", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x4F, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x50, Mnemonic: "BVC", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x51, Mnemonic: "EOR", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0x52, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x53, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x54, Mnemonic: "NO2", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x55, Mnemonic: "EOR", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x56, Mnemonic: "LSR", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x57, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x58, Mnemonic: "CLI", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x59, Mnemonic: "EOR", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0x5A, Mnemonic: "NO1", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x5B, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x5C, Mnemonic: "NO3", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x5D, Mnemonic: "EOR", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x5E, Mnemonic: "LSR", Cycles: 7, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x5F, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x60, Mnemonic: "RTS", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x61, Mnemonic: "ADC", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0x62, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x63, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x64, Mnemonic: "NO2", Cycles: 3, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x65, Mnemonic: "ADC", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x66, Mnemonic: "ROR", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x67, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x68, Mnemonic: "PLA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x69, Mnemonic: "ADC", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0x6A, Mnemonic: "ROR", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x6B, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x6C, Mnemonic: "JMP", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirect },
	{ Opcode: 0x6D, Mnemonic: "ADC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x6E, Mnemonic: "ROR", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x6F, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x70, Mnemonic: "BVS", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x71, Mnemonic: "ADC", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0x72, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x73, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x74, Mnemonic: "NO2", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x75, Mnemonic: "ADC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x76, Mnemonic: "ROR", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x77, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x78, Mnemonic: "SEI", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x79, Mnemonic: "ADC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0x7A, Mnemonic: "NO1", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x7B, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x7C, Mnemonic: "NO3", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x7D, Mnemonic: "ADC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x7E, Mnemonic: "ROR", Cycles: 7, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x7F, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x80, Mnemonic: "NO2", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x81, Mnemonic: "STA", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0x82, Mnemonic: "NO2", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x83, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x84, Mnemonic: "STY", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x85, Mnemonic: "STA", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x86, Mnemonic: "STX", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0x87, Mnemonic: ""   , Cycles: 3, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x88, Mnemonic: "DEY", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x89, Mnemonic: "NO2", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x8A, Mnemonic: "TXA", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0x8B, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x8C, Mnemonic: "STY", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x8D, Mnemonic: "STA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x8E, Mnemonic: "STX", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0x8F, Mnemonic: ""   , Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x90, Mnemonic: "BCC", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x91, Mnemonic: "STA", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0x92, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x93, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x94, Mnemonic: "STY", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x95, Mnemonic: "STA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0x96, Mnemonic: "STX", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageY },
	{ Opcode: 0x97, Mnemonic: ""   , Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x98, Mnemonic: "TYA", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0x99, Mnemonic: "STA", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0x9A, Mnemonic: "TXS", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0x9B, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x9C, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x9D, Mnemonic: "STA", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0x9E, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0x9F, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xA0, Mnemonic: "LDY", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xA1, Mnemonic: "LDA", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0xA2, Mnemonic: "LDX", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xA3, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xA4, Mnemonic: "LDY", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xA5, Mnemonic: "LDA", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xA6, Mnemonic: "LDX", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xA7, Mnemonic: ""   , Cycles: 3, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xA8, Mnemonic: "TAY", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xA9, Mnemonic: "LDA", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xAA, Mnemonic: "TAX", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xAB, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xAC, Mnemonic: "LDY", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xAD, Mnemonic: "LDA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xAE, Mnemonic: "LDX", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xAF, Mnemonic: ""   , Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xB0, Mnemonic: "BCS", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xB1, Mnemonic: "LDA", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0xB2, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xB3, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xB4, Mnemonic: "LDY", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0xB5, Mnemonic: "LDA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0xB6, Mnemonic: "LDX", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageY },
	{ Opcode: 0xB7, Mnemonic: ""   , Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xB8, Mnemonic: "CLV", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xB9, Mnemonic: "LDA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0xBA, Mnemonic: "TSX", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xBB, Mnemonic: ""   , Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xBC, Mnemonic: "LDY", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0xBD, Mnemonic: "LDA", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0xBE, Mnemonic: "LDX", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0xBF, Mnemonic: ""   , Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xC0, Mnemonic: "CPY", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xC1, Mnemonic: "CMP", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0xC2, Mnemonic: "NO2", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xC3, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xC4, Mnemonic: "CPY", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xC5, Mnemonic: "CMP", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xC6, Mnemonic: "DEC", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xC7, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xC8, Mnemonic: "INY", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xC9, Mnemonic: "CMP", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xCA, Mnemonic: "DEX", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xCB, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xCC, Mnemonic: "CPY", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xCD, Mnemonic: "CMP", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xCE, Mnemonic: "DEC", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xCF, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xD0, Mnemonic: "BNE", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xD1, Mnemonic: "CMP", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0xD2, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xD3, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xD4, Mnemonic: "NO2", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xD5, Mnemonic: "CMP", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0xD6, Mnemonic: "DEC", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0xD7, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xD8, Mnemonic: "CLD", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xD9, Mnemonic: "CMP", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0xDA, Mnemonic: "NO1", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xDB, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xDC, Mnemonic: "NO3", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xDD, Mnemonic: "CMP", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0xDE, Mnemonic: "DEC", Cycles: 7, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0xDF, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xE0, Mnemonic: "CPX", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xE1, Mnemonic: "SBC", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgIndexedIndirectX },
	{ Opcode: 0xE2, Mnemonic: "NO2", Cycles: 3, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xE3, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xE4, Mnemonic: "CPX", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xE5, Mnemonic: "SBC", Cycles: 3, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xE6, Mnemonic: "INC", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgZeroPage },
	{ Opcode: 0xE7, Mnemonic: ""   , Cycles: 5, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xE8, Mnemonic: "INX", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xE9, Mnemonic: "SBC", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgImmediate },
	{ Opcode: 0xEA, Mnemonic: "NOP", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xEB, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xEC, Mnemonic: "CPX", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xED, Mnemonic: "SBC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xEE, Mnemonic: "INC", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgAbsolute },
	{ Opcode: 0xEF, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xF0, Mnemonic: "BEQ", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xF1, Mnemonic: "SBC", Cycles: 5, Documented: true,  Addressing: (*CPU).DbgIndirectIndexedY },
	{ Opcode: 0xF2, Mnemonic: ""   , Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xF3, Mnemonic: ""   , Cycles: 8, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xF4, Mnemonic: "NO2", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xF5, Mnemonic: "SBC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0xF6, Mnemonic: "INC", Cycles: 6, Documented: true,  Addressing: (*CPU).DbgZeroPageX },
	{ Opcode: 0xF7, Mnemonic: ""   , Cycles: 6, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xF8, Mnemonic: "SED", Cycles: 2, Documented: true,  Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xF9, Mnemonic: "SBC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteY },
	{ Opcode: 0xFA, Mnemonic: "NO1", Cycles: 2, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xFB, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xFC, Mnemonic: "NO3", Cycles: 4, Documented: false, Addressing: (*CPU).DbgNoAddressing },
	{ Opcode: 0xFD, Mnemonic: "SBC", Cycles: 4, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0xFE, Mnemonic: "INC", Cycles: 7, Documented: true,  Addressing: (*CPU).DbgAbsoluteX },
	{ Opcode: 0xFF, Mnemonic: ""   , Cycles: 7, Documented: false, Addressing: (*CPU).DbgNoAddressing },
}
